// generated by github.com/newlix/testingdart
// go get github.com/dnephin/filewatcher
// filewatcher -x . testingdart
import 'package:testing/testing.dart' as testing;
import 'lambda_test.dart' as _lambda;

Future<bool> pass({bool verbose}) async {
  testing.verbose = verbose;

  testing.start();

  await testing.run('testInvokeHello', _lambda.testInvokeHello);
  await testing.run('testInvokeUnknown', _lambda.testInvokeUnknown);

  testing.end();

  return testing.pass;
}
