// generated by gentest
// usage:
// go get github.com/newlix/gentest
// go get github.com/dnephin/filewatcher
// filewatcher -x . gentest
import 'package:testing/testing.dart' as testing;
import 'lambda_test.dart' as _lambda;

Future<int> run() async {
  testing.verbose = true;
  await testing.run('testInvokeHello', _lambda.testInvokeHello);
  await testing.run('testInvokeUnknown', _lambda.testInvokeUnknown);

  return testing.errorCount;
}
