// generated by gentest
// usage:
// go get github.com/newlix/gentest
// go get github.com/dnephin/filewatcher
// filewatcher -x . gentest lambda
import 'package:lambda/tests.dart' as tests;

void main() async {
  await tests.pass(verbose: true);
}
